# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CAM_Desinger_GUI_2.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGraphicsView, QGroupBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(795, 592)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 10, 781, 31))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(610, 70, 191, 481))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setLineWidth(2)
        self.GcodeBot = QPushButton(self.frame)
        self.GcodeBot.setObjectName(u"GcodeBot")
        self.GcodeBot.setGeometry(QRect(20, 440, 81, 31))
        self.GcodeBot.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_16 = QLabel(self.frame)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 0, 191, 31))
        font1 = QFont()
        font1.setPointSize(13)
        font1.setBold(True)
        font1.setKerning(True)
        self.label_16.setFont(font1)
        self.label_16.setScaledContents(True)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.groupBox = QGroupBox(self.frame)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 40, 151, 61))
        font2 = QFont()
        font2.setBold(True)
        self.groupBox.setFont(font2)
        self.groupBox.setAlignment(Qt.AlignCenter)
        self.YCenter = QLineEdit(self.groupBox)
        self.YCenter.setObjectName(u"YCenter")
        self.YCenter.setGeometry(QRect(80, 30, 61, 20))
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 20, 61, 16))
        font3 = QFont()
        font3.setBold(False)
        self.label_17.setFont(font3)
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(80, 20, 61, 16))
        self.label_18.setFont(font3)
        self.CenterX = QLineEdit(self.groupBox)
        self.CenterX.setObjectName(u"CenterX")
        self.CenterX.setGeometry(QRect(10, 30, 61, 20))
        self.YCenter.raise_()
        self.label_18.raise_()
        self.CenterX.raise_()
        self.label_17.raise_()
        self.groupBox_2 = QGroupBox(self.frame)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 110, 151, 101))
        self.groupBox_2.setFont(font2)
        self.groupBox_2.setAlignment(Qt.AlignCenter)
        self.ZFR = QLineEdit(self.groupBox_2)
        self.ZFR.setObjectName(u"ZFR")
        self.ZFR.setGeometry(QRect(10, 70, 131, 20))
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 20, 91, 16))
        self.label_19.setFont(font3)
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 60, 131, 16))
        self.label_20.setFont(font3)
        self.Passes = QLineEdit(self.groupBox_2)
        self.Passes.setObjectName(u"Passes")
        self.Passes.setGeometry(QRect(10, 30, 131, 20))
        self.ZFR.raise_()
        self.Passes.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.groupBox_3 = QGroupBox(self.frame)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 220, 151, 61))
        self.groupBox_3.setFont(font2)
        self.groupBox_3.setAlignment(Qt.AlignCenter)
        self.Direction = QComboBox(self.groupBox_3)
        self.Direction.addItem("")
        self.Direction.addItem("")
        self.Direction.setObjectName(u"Direction")
        self.Direction.setGeometry(QRect(10, 30, 131, 22))
        self.Direction.setFont(font3)
        self.groupBox_4 = QGroupBox(self.frame)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 290, 151, 141))
        self.groupBox_4.setFont(font2)
        self.groupBox_4.setAlignment(Qt.AlignCenter)
        self.Offset = QComboBox(self.groupBox_4)
        self.Offset.addItem("")
        self.Offset.addItem("")
        self.Offset.setObjectName(u"Offset")
        self.Offset.setGeometry(QRect(10, 70, 131, 22))
        self.Offset.setFont(font3)
        self.Diameter = QLineEdit(self.groupBox_4)
        self.Diameter.setObjectName(u"Diameter")
        self.Diameter.setGeometry(QRect(10, 30, 131, 20))
        self.label_23 = QLabel(self.groupBox_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 20, 91, 16))
        self.label_23.setFont(font3)
        self.label_24 = QLabel(self.groupBox_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 60, 91, 16))
        self.label_24.setFont(font3)
        self.ToolFR = QLineEdit(self.groupBox_4)
        self.ToolFR.setObjectName(u"ToolFR")
        self.ToolFR.setGeometry(QRect(10, 110, 131, 20))
        self.label_25 = QLabel(self.groupBox_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 100, 91, 16))
        self.label_25.setFont(font3)
        self.graphicsView = QGraphicsView(self.frame)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(120, 440, 31, 31))
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(20, 10, 591, 541))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.D2 = QLineEdit(self.frame_2)
        self.D2.setObjectName(u"D2")
        self.D2.setGeometry(QRect(10, 210, 113, 20))
        self.CAMPlot = QFrame(self.frame_2)
        self.CAMPlot.setObjectName(u"CAMPlot")
        self.CAMPlot.setGeometry(QRect(140, 49, 431, 431))
        self.CAMPlot.setFrameShape(QFrame.StyledPanel)
        self.CAMPlot.setFrameShadow(QFrame.Raised)
        self.RiseProfile = QComboBox(self.frame_2)
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.setObjectName(u"RiseProfile")
        self.RiseProfile.setGeometry(QRect(10, 370, 111, 22))
        self.label = QLabel(self.frame_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 111, 16))
        self.FallProfile = QComboBox(self.frame_2)
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.setObjectName(u"FallProfile")
        self.FallProfile.setGeometry(QRect(10, 410, 111, 22))
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 280, 111, 16))
        self.STLBot = QPushButton(self.frame_2)
        self.STLBot.setObjectName(u"STLBot")
        self.STLBot.setGeometry(QRect(260, 500, 111, 31))
        self.STLBot.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ImportBot = QPushButton(self.frame_2)
        self.ImportBot.setObjectName(u"ImportBot")
        self.ImportBot.setGeometry(QRect(10, 510, 51, 21))
        self.ImportBot.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 320, 111, 16))
        self.D3 = QLineEdit(self.frame_2)
        self.D3.setObjectName(u"D3")
        self.D3.setGeometry(QRect(10, 250, 113, 20))
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 160, 111, 16))
        self.ExportBot = QPushButton(self.frame_2)
        self.ExportBot.setObjectName(u"ExportBot")
        self.ExportBot.setGeometry(QRect(70, 510, 51, 21))
        self.ExportBot.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_12 = QLabel(self.frame_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 500, 111, 16))
        self.label_6 = QLabel(self.frame_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 240, 111, 16))
        self.D1 = QLineEdit(self.frame_2)
        self.D1.setObjectName(u"D1")
        self.D1.setGeometry(QRect(10, 170, 113, 20))
        self.D4 = QLineEdit(self.frame_2)
        self.D4.setObjectName(u"D4")
        self.D4.setGeometry(QRect(10, 290, 113, 20))
        self.TR = QLineEdit(self.frame_2)
        self.TR.setObjectName(u"TR")
        self.TR.setGeometry(QRect(10, 90, 113, 20))
        self.label_5 = QLabel(self.frame_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 200, 111, 16))
        self.label_10 = QLabel(self.frame_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 360, 111, 16))
        self.Thickness = QLineEdit(self.frame_2)
        self.Thickness.setObjectName(u"Thickness")
        self.Thickness.setGeometry(QRect(10, 130, 113, 20))
        self.GraphBot = QPushButton(self.frame_2)
        self.GraphBot.setObjectName(u"GraphBot")
        self.GraphBot.setGeometry(QRect(140, 500, 111, 31))
        self.GraphBot.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 80, 111, 16))
        self.BR = QLineEdit(self.frame_2)
        self.BR.setObjectName(u"BR")
        self.BR.setGeometry(QRect(10, 50, 113, 20))
        self.label_3 = QLabel(self.frame_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 120, 111, 16))
        self.Tri = QLineEdit(self.frame_2)
        self.Tri.setObjectName(u"Tri")
        self.Tri.setGeometry(QRect(10, 330, 113, 20))
        self.label_11 = QLabel(self.frame_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 400, 111, 16))
        self.checkBox = QCheckBox(self.frame_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(40, 440, 61, 16))
        self.label_13 = QLabel(self.frame_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 460, 111, 16))
        self.HoleD = QLineEdit(self.frame_2)
        self.HoleD.setObjectName(u"HoleD")
        self.HoleD.setGeometry(QRect(10, 470, 113, 20))
        self.lineEdit = QLineEdit(self.frame_2)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(380, 510, 211, 20))
        self.HoleD.raise_()
        self.D2.raise_()
        self.CAMPlot.raise_()
        self.RiseProfile.raise_()
        self.FallProfile.raise_()
        self.STLBot.raise_()
        self.ImportBot.raise_()
        self.D3.raise_()
        self.ExportBot.raise_()
        self.label_12.raise_()
        self.label_6.raise_()
        self.D1.raise_()
        self.D4.raise_()
        self.TR.raise_()
        self.label_5.raise_()
        self.label_10.raise_()
        self.Thickness.raise_()
        self.GraphBot.raise_()
        self.label_2.raise_()
        self.BR.raise_()
        self.label_3.raise_()
        self.Tri.raise_()
        self.label_11.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.checkBox.raise_()
        self.label_13.raise_()
        self.lineEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.frame_2.raise_()
        self.label_9.raise_()
        self.frame.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 795, 20))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"CAM Designer", None))
        self.GcodeBot.setText(QCoreApplication.translate("MainWindow", u"Generate G-Code", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"CAM G-Code", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"CAM Center Global Position", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"CAM Z Settings", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Number of Passes", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Feed Rate (IPM)", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Direction", None))
        self.Direction.setItemText(0, QCoreApplication.translate("MainWindow", u"Clockwise", None))
        self.Direction.setItemText(1, QCoreApplication.translate("MainWindow", u"Counter Clockwise", None))

        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Tool", None))
        self.Offset.setItemText(0, QCoreApplication.translate("MainWindow", u"Inside", None))
        self.Offset.setItemText(1, QCoreApplication.translate("MainWindow", u"Outside", None))

        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Diameter", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Offset", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Feed Rate (IPM)", None))
        self.RiseProfile.setItemText(0, QCoreApplication.translate("MainWindow", u"Linear", None))
        self.RiseProfile.setItemText(1, QCoreApplication.translate("MainWindow", u"Parabolic", None))
        self.RiseProfile.setItemText(2, QCoreApplication.translate("MainWindow", u"Harmonic", None))
        self.RiseProfile.setItemText(3, QCoreApplication.translate("MainWindow", u"Cycloidal", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"Base Radius (mm)", None))
        self.FallProfile.setItemText(0, QCoreApplication.translate("MainWindow", u"Linear", None))
        self.FallProfile.setItemText(1, QCoreApplication.translate("MainWindow", u"Parabolic", None))
        self.FallProfile.setItemText(2, QCoreApplication.translate("MainWindow", u"Harmonic", None))
        self.FallProfile.setItemText(3, QCoreApplication.translate("MainWindow", u"Cycloidal", None))

        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Degrees to Dwell", None))
        self.STLBot.setText(QCoreApplication.translate("MainWindow", u"Generate CAD Model", None))
        self.ImportBot.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Number of Triangles", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Degrees to Rise", None))
        self.ExportBot.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Import/Export Settings", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Degrees to Fall", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Degrees to Dwell", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Rise Profile", None))
        self.GraphBot.setText(QCoreApplication.translate("MainWindow", u"Generate Graph", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Travel Radius (mm)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Thickness (mm)", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Fall Profile", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Add Hole", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Hole Diameter", None))
    # retranslateUi

