# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CAM_Desinger_GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(750, 550)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Thickness = QLineEdit(self.centralwidget)
        self.Thickness.setObjectName(u"Thickness")
        self.Thickness.setGeometry(QRect(20, 130, 113, 20))
        self.D1 = QLineEdit(self.centralwidget)
        self.D1.setObjectName(u"D1")
        self.D1.setGeometry(QRect(20, 170, 113, 20))
        self.D2 = QLineEdit(self.centralwidget)
        self.D2.setObjectName(u"D2")
        self.D2.setGeometry(QRect(20, 210, 113, 20))
        self.D3 = QLineEdit(self.centralwidget)
        self.D3.setObjectName(u"D3")
        self.D3.setGeometry(QRect(20, 250, 113, 20))
        self.D4 = QLineEdit(self.centralwidget)
        self.D4.setObjectName(u"D4")
        self.D4.setGeometry(QRect(20, 290, 113, 20))
        self.Tri = QLineEdit(self.centralwidget)
        self.Tri.setObjectName(u"Tri")
        self.Tri.setGeometry(QRect(20, 330, 113, 20))
        self.TR = QLineEdit(self.centralwidget)
        self.TR.setObjectName(u"TR")
        self.TR.setGeometry(QRect(20, 90, 113, 20))
        self.BR = QLineEdit(self.centralwidget)
        self.BR.setObjectName(u"BR")
        self.BR.setGeometry(QRect(20, 50, 113, 20))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 40, 111, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 80, 111, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 120, 111, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 160, 111, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 200, 111, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 240, 111, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 280, 111, 16))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 320, 111, 16))
        self.GraphBot = QPushButton(self.centralwidget)
        self.GraphBot.setObjectName(u"GraphBot")
        self.GraphBot.setGeometry(QRect(150, 430, 111, 31))
        self.GraphBot.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 10, 721, 21))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.STLBot = QPushButton(self.centralwidget)
        self.STLBot.setObjectName(u"STLBot")
        self.STLBot.setGeometry(QRect(300, 430, 111, 31))
        self.STLBot.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.RiseProfile = QComboBox(self.centralwidget)
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.setObjectName(u"RiseProfile")
        self.RiseProfile.setGeometry(QRect(20, 370, 111, 22))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 360, 111, 16))
        self.FallProfile = QComboBox(self.centralwidget)
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.setObjectName(u"FallProfile")
        self.FallProfile.setGeometry(QRect(20, 410, 111, 22))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 400, 111, 16))
        self.STEPBot = QPushButton(self.centralwidget)
        self.STEPBot.setObjectName(u"STEPBot")
        self.STEPBot.setGeometry(QRect(450, 430, 111, 31))
        self.STEPBot.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.CAMPlot = QFrame(self.centralwidget)
        self.CAMPlot.setObjectName(u"CAMPlot")
        self.CAMPlot.setGeometry(QRect(150, 49, 411, 361))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CAMPlot.sizePolicy().hasHeightForWidth())
        self.CAMPlot.setSizePolicy(sizePolicy)
        self.CAMPlot.setFrameShape(QFrame.StyledPanel)
        self.CAMPlot.setFrameShadow(QFrame.Raised)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 750, 20))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Base Radius", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Travel Radius", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Thickness", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Degrees to Rise", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Degrees to Dwell", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Degrees to Fall", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Degrees to Dwell", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Number of Triangles", None))
        self.GraphBot.setText(QCoreApplication.translate("MainWindow", u"Generate Graph", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"CAM Designer", None))
        self.STLBot.setText(QCoreApplication.translate("MainWindow", u"Generate STL", None))
        self.RiseProfile.setItemText(0, QCoreApplication.translate("MainWindow", u"Linear", None))
        self.RiseProfile.setItemText(1, QCoreApplication.translate("MainWindow", u"Parabolic", None))
        self.RiseProfile.setItemText(2, QCoreApplication.translate("MainWindow", u"Harmonic", None))
        self.RiseProfile.setItemText(3, QCoreApplication.translate("MainWindow", u"Cycloidal", None))

        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Rise Profile", None))
        self.FallProfile.setItemText(0, QCoreApplication.translate("MainWindow", u"Linear", None))
        self.FallProfile.setItemText(1, QCoreApplication.translate("MainWindow", u"Parabolic", None))
        self.FallProfile.setItemText(2, QCoreApplication.translate("MainWindow", u"Harmonic", None))
        self.FallProfile.setItemText(3, QCoreApplication.translate("MainWindow", u"Cycloidal", None))

        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Fall Profile", None))
        self.STEPBot.setText(QCoreApplication.translate("MainWindow", u"Generate STEP", None))
    # retranslateUi

