# Form implementation generated from reading ui file 'CAM_Desinger_GUI_2.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 514)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Thickness = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Thickness.setGeometry(QtCore.QRect(20, 130, 113, 20))
        self.Thickness.setObjectName("Thickness")
        self.D1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.D1.setGeometry(QtCore.QRect(20, 170, 113, 20))
        self.D1.setObjectName("D1")
        self.D2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.D2.setGeometry(QtCore.QRect(20, 210, 113, 20))
        self.D2.setObjectName("D2")
        self.D3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.D3.setGeometry(QtCore.QRect(20, 250, 113, 20))
        self.D3.setObjectName("D3")
        self.D4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.D4.setGeometry(QtCore.QRect(20, 290, 113, 20))
        self.D4.setObjectName("D4")
        self.Tri = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Tri.setGeometry(QtCore.QRect(20, 330, 113, 20))
        self.Tri.setObjectName("Tri")
        self.TR = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.TR.setGeometry(QtCore.QRect(20, 90, 113, 20))
        self.TR.setObjectName("TR")
        self.BR = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.BR.setGeometry(QtCore.QRect(20, 50, 113, 20))
        self.BR.setObjectName("BR")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 280, 111, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 320, 111, 16))
        self.label_8.setObjectName("label_8")
        self.GraphBot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GraphBot.setGeometry(QtCore.QRect(150, 440, 111, 31))
        self.GraphBot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.GraphBot.setObjectName("GraphBot")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 641, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.STLBot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.STLBot.setGeometry(QtCore.QRect(280, 440, 111, 31))
        self.STLBot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.STLBot.setObjectName("STLBot")
        self.RiseProfile = QtWidgets.QComboBox(parent=self.centralwidget)
        self.RiseProfile.setGeometry(QtCore.QRect(20, 370, 111, 22))
        self.RiseProfile.setObjectName("RiseProfile")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 360, 111, 16))
        self.label_10.setObjectName("label_10")
        self.FallProfile = QtWidgets.QComboBox(parent=self.centralwidget)
        self.FallProfile.setGeometry(QtCore.QRect(20, 410, 111, 22))
        self.FallProfile.setObjectName("FallProfile")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 400, 111, 16))
        self.label_11.setObjectName("label_11")
        self.STEPBot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.STEPBot.setGeometry(QtCore.QRect(410, 440, 111, 31))
        self.STEPBot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.STEPBot.setObjectName("STEPBot")
        self.CAMPlot = QtWidgets.QFrame(parent=self.centralwidget)
        self.CAMPlot.setGeometry(QtCore.QRect(150, 49, 501, 381))
        self.CAMPlot.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.CAMPlot.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.CAMPlot.setObjectName("CAMPlot")
        self.GcodeBot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GcodeBot.setGeometry(QtCore.QRect(540, 440, 111, 31))
        self.GcodeBot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.GcodeBot.setObjectName("GcodeBot")
        self.ImportBot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ImportBot.setGeometry(QtCore.QRect(20, 450, 51, 21))
        self.ImportBot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ImportBot.setObjectName("ImportBot")
        self.ExportBot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ExportBot.setGeometry(QtCore.QRect(80, 450, 51, 21))
        self.ExportBot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ExportBot.setObjectName("ExportBot")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 440, 111, 16))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Base Radius (mm)"))
        self.label_2.setText(_translate("MainWindow", "Travel Radius (mm)"))
        self.label_3.setText(_translate("MainWindow", "Thickness (mm)"))
        self.label_4.setText(_translate("MainWindow", "Degrees to Rise"))
        self.label_5.setText(_translate("MainWindow", "Degrees to Dwell"))
        self.label_6.setText(_translate("MainWindow", "Degrees to Fall"))
        self.label_7.setText(_translate("MainWindow", "Degrees to Dwell"))
        self.label_8.setText(_translate("MainWindow", "Number of Triangles"))
        self.GraphBot.setText(_translate("MainWindow", "Generate Graph"))
        self.label_9.setText(_translate("MainWindow", "CAM Designer"))
        self.STLBot.setText(_translate("MainWindow", "Generate STL"))
        self.RiseProfile.setItemText(0, _translate("MainWindow", "Linear"))
        self.RiseProfile.setItemText(1, _translate("MainWindow", "Parabolic"))
        self.RiseProfile.setItemText(2, _translate("MainWindow", "Harmonic"))
        self.RiseProfile.setItemText(3, _translate("MainWindow", "Cycloidal"))
        self.label_10.setText(_translate("MainWindow", "Rise Profile"))
        self.FallProfile.setItemText(0, _translate("MainWindow", "Linear"))
        self.FallProfile.setItemText(1, _translate("MainWindow", "Parabolic"))
        self.FallProfile.setItemText(2, _translate("MainWindow", "Harmonic"))
        self.FallProfile.setItemText(3, _translate("MainWindow", "Cycloidal"))
        self.label_11.setText(_translate("MainWindow", "Fall Profile"))
        self.STEPBot.setText(_translate("MainWindow", "Generate STEP"))
        self.GcodeBot.setText(_translate("MainWindow", "Generate G-Code"))
        self.ImportBot.setText(_translate("MainWindow", "Import"))
        self.ExportBot.setText(_translate("MainWindow", "Export"))
        self.label_12.setText(_translate("MainWindow", "Import/Export Settings"))

        ### Action Items ###

        # Graphing button
        from CAM_Func import CAMPlot
        self.GraphBot.clicked.connect(lambda: CAMPlot(self)) # graph button must be called GraphBot
        self.STLBot.clicked.connect(self.STLSave) # STL button must be called STLBot
        self.STEPBot.clicked.connect(self.STPSave) # STEP Button must be called STEPBot
        
    def STLSave(self):
        from CAM_Func import STLFileName

        filename = STLFileName(self.centralwidget)
        if filename:
            print("Save to:", filename)
            from CAM_Func import STLGen, CAMPlot
            angle,Y,Thickness=CAMPlot(self)
            STLGen(angle, Y, Thickness,filename)

        # Do something with filename, like saving a file
        else:
            print("No file selected.")
        
    def STPSave(self):
        from CAM_Func import STPFileName

        filename = STPFileName(self.centralwidget)
        if filename:
            print("Save to:", filename)
            from CAM_Func import STPGen, CAMPlot
            angle,Y,Thickness=CAMPlot(self)
            STPGen(angle, Y, Thickness,filename)

        # Do something with filename, like saving a file
        else:
            print("No file selected.")

        


    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())