# Form implementation generated from reading ui file 'CAM_desinger_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
#import PySide6
#import PySide6.QtCore

#print(PySide6.__version__)
#print(PySide6.QtCore.__version__) # type: ignore

#from CAM_Func import Harmonic,Linear,Parabolic,Cycloidal,CAMPolPlot,STLGen


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 515)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Thickness = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Thickness.setGeometry(QtCore.QRect(20, 130, 113, 20))
        self.Thickness.setObjectName("Thickness")
        self.D1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.D1.setGeometry(QtCore.QRect(20, 170, 113, 20))
        self.D1.setObjectName("D1")
        self.D2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.D2.setGeometry(QtCore.QRect(20, 210, 113, 20))
        self.D2.setObjectName("D2")
        self.D3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.D3.setGeometry(QtCore.QRect(20, 250, 113, 20))
        self.D3.setObjectName("D3")
        self.D4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.D4.setGeometry(QtCore.QRect(20, 290, 113, 20))
        self.D4.setObjectName("D4")
        self.Tri = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Tri.setGeometry(QtCore.QRect(20, 330, 113, 20))
        self.Tri.setObjectName("Tri")
        self.TR = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.TR.setGeometry(QtCore.QRect(20, 90, 113, 20))
        self.TR.setObjectName("TR")
        self.BR = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.BR.setGeometry(QtCore.QRect(20, 50, 113, 20))
        self.BR.setObjectName("BR")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 280, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 320, 81, 16))
        self.label_8.setObjectName("label_8")
        self.Graph = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Graph.setGeometry(QtCore.QRect(160, 430, 101, 31))
        self.Graph.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Graph.setObjectName("Graph")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.Graph_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Graph_2.setGeometry(QtCore.QRect(300, 430, 111, 31))
        self.Graph_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Graph_2.setObjectName("Graph_2")
        self.RiseProfile = QtWidgets.QComboBox(parent=self.centralwidget)
        self.RiseProfile.setGeometry(QtCore.QRect(20, 370, 111, 22))
        self.RiseProfile.setObjectName("RiseProfile")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.RiseProfile.addItem("")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 360, 81, 16))
        self.label_10.setObjectName("label_10")
        self.FallProfile = QtWidgets.QComboBox(parent=self.centralwidget)
        self.FallProfile.setGeometry(QtCore.QRect(20, 410, 111, 22))
        self.FallProfile.setObjectName("FallProfile")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.FallProfile.addItem("")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 400, 81, 16))
        self.label_11.setObjectName("label_11")
        self.Graph_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Graph_3.setGeometry(QtCore.QRect(450, 430, 111, 31))
        self.Graph_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Graph_3.setObjectName("Graph_3")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(150, 49, 401, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Base Radius"))
        self.label_2.setText(_translate("MainWindow", "Travel Radius"))
        self.label_3.setText(_translate("MainWindow", "Thickness"))
        self.label_4.setText(_translate("MainWindow", "Degrees to Rise"))
        self.label_5.setText(_translate("MainWindow", "Degrees to Dwell"))
        self.label_6.setText(_translate("MainWindow", "Degrees to Fall"))
        self.label_7.setText(_translate("MainWindow", "Degrees to Dwell"))
        self.label_8.setText(_translate("MainWindow", "Number of Triangles"))
        self.Graph.setText(_translate("MainWindow", "Generate Graph"))
        self.label_9.setText(_translate("MainWindow", "CAM Designer"))
        self.Graph_2.setText(_translate("MainWindow", "Generate STL"))
        self.RiseProfile.setItemText(0, _translate("MainWindow", "Linear"))
        self.RiseProfile.setItemText(1, _translate("MainWindow", "Parabolic"))
        self.RiseProfile.setItemText(2, _translate("MainWindow", "Harmonic"))
        self.RiseProfile.setItemText(3, _translate("MainWindow", "Cycloidal"))
        self.label_10.setText(_translate("MainWindow", "Rise Profile"))
        self.FallProfile.setItemText(0, _translate("MainWindow", "Linear"))
        self.FallProfile.setItemText(1, _translate("MainWindow", "Parabolic"))
        self.FallProfile.setItemText(2, _translate("MainWindow", "Harmonic"))
        self.FallProfile.setItemText(3, _translate("MainWindow", "Cycloidal"))
        self.label_11.setText(_translate("MainWindow", "Fall Profile"))
        self.Graph_3.setText(_translate("MainWindow", "Generate STEP"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

        self.Graph_2.clicked.connect(self.Plot)


    def Plot(self):
        from CAMs.CAM_Func import Harmonic,Linear,Parabolic,Cycloidal,CAMPolPlot,STLGen,CAMPolPlotFall,CAMPolPlotRise
        import matplotlib.pyplot as plt

        TR=self.TR.text()
        TR=int(float(TR))
        D1=self.D1.text()
        D1=int(float(D1))
        D2=self.D2.text()
        D2=int(float(D2))
        D3=self.D3.text()
        D3=int(float(D3))
        D4=self.D4.text()
        D4=int(float(D4))
        Tri=self.Tri.text()
        Tri=int(float(Tri))
        BR=self.BR.text()
        BR=int(float(BR))
        Thickness=self.Thickness.text()
        Thickness=int(float(Thickness))
        Df=[0,D1,D2,D3,D4]

        RisePro=str(self.RiseProfile.currentText())
        FallPro=str(self.FallProfile.currentText())

        ### Polar Plotting ###
        fig2, plot = plt.subplots(subplot_kw={'projection': 'polar'})

        ### Rise Profile ###
        if RisePro=="Harmonic":
            angle=Harmonic(TR,Df,BR,Tri)[1]
            Y=Harmonic(TR,Df,BR,Tri)[0]
            plot.plot(angle[0], Y[0])
            plot.plot(angle[1], Y[1])

        elif RisePro=="Linear":
            angle=Linear(TR,Df,BR,Tri)[1]
            Y=Linear(TR,Df,BR,Tri)[0]
            plot.plot(angle[0], Y[0])
            plot.plot(angle[1], Y[1])

        elif RisePro=="Parabolic":
            angle=Parabolic(TR,Df,BR,Tri)[1]
            Y=Parabolic(TR,Df,BR,Tri)[0]
            plot.plot(angle[0], Y[0])
            plot.plot(angle[1], Y[1])

        elif RisePro=="Cycloidal":
            angle=Cycloidal(TR,Df,BR,Tri)[1]
            Y=Cycloidal(TR,Df,BR,Tri)[0]
            plot.plot(angle[0], Y[0])
            plot.plot(angle[1], Y[1])

        ### Fall Profile ###
        if FallPro=="Harmonic":
            angle=Harmonic(TR,Df,BR,Tri)[1]
            Y=Harmonic(TR,Df,BR,Tri)[0]
            plot.plot(angle[2], Y[2])
            plot.plot(angle[3], Y[3])
        elif FallPro=="Linear":
            angle=Linear(TR,Df,BR,Tri)[1]
            Y=Linear(TR,Df,BR,Tri)[0]
            plot.plot(angle[2], Y[2])
            plot.plot(angle[3], Y[3])
        elif FallPro=="Parabolic":
            angle=Parabolic(TR,Df,BR,Tri)[1]
            Y=Parabolic(TR,Df,BR,Tri)[0]
            plot.plot(angle[2], Y[2])
            plot.plot(angle[3], Y[3])
        elif FallPro=="Cycloidal":
            angle=Cycloidal(TR,Df,BR,Tri)[1]
            Y=Cycloidal(TR,Df,BR,Tri)[0]
            plot.plot(angle[2], Y[2])
            plot.plot(angle[3], Y[3])
        
        plt.show()
        
        #self.D1.setText("changes")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
